title: "Shadi Barakat"
logo: "/images/photo.jpeg"
description: "Exploring technology, coding, and creative projects"
show_downloads: true
theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
