# Site settings
title: Shadi Barakat Portfolio
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://shadibarakat.github.io" # The base hostname & protocol for your site

# Contact Information
email: shadibarakat2004@gmail.com
github_username: shadibarakat
linkedin_username: shadibarakat

# SEO settings
google_analytics: UA-XXXXXXX-X # Replace with your Google Analytics tracking ID
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap # Generates a sitemap.xml file for SEO
  - jekyll-feed # Adds RSS feed support

# Theme settings
theme: minima # Replace with your preferred Jekyll theme

# Social Links
social_links:
  github: "https://github.com/shadibarakat"
  linkedin: "https://linkedin.com/in/shadi-barakat-781408265/"

# Portfolio settings
portfolio:
  - title: "GameGo Checkout System"
    description: "An intricate checkout system for a fictional store with multiple features."
    url: "/projects/gamego"
    image: "/assets/images/gamego-thumbnail.png"
  - title: "Blackjack Game"
    description: "A simple blackjack game with a UI in progress."
    url: "/projects/blackjack"
    image: "/assets/images/blackjack-thumbnail.png"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude these files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# New Settings for Aesthetics and Performance
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true # Enable comments for posts
      image: "/assets/images/default-thumbnail.png" # Default thumbnail image for posts

# Additional configuration options
paginate: 5 # Number of posts per page
paginate_path: "/page:num/"
permalink: "/:title/" # Set clean URLs
