
title: Shadi Barakat
logo: /images/photo.jpeg
description: Exploring technology, coding, and creative projects
show_downloads: true
theme: jekyll-theme-minimal

# Add SEO optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
social_links:
  - name: GitHub
    url: https://github.com/shadibarakat
    icon: fa-github
  - name: LinkedIn
    url: https://www.linkedin.com/in/shadi-barakat-781408265/
    icon: fa-linkedin

  - name: Email
    url: mailto:your.email@example.com
    icon: fa-envelope


# Customization of the theme colors (optional)
theme_colors:
  background: "#f5f5f5"
  text: "#333333"
  accent: "#007acc"
  link: "#007acc"
