# Site settings
title: "Shadi Barakat"
logo: "/images/photo.jpeg" # Path to your logo image
description: "A journey through technology, coding, and creative projects."
theme: jekyll-theme-minimal
show_downloads: true

# Author settings
author: "Shadi Barakat"
email: "shadibarakat2004@gmail.com"
github_username: "shadibarakat"

# Social links
social_links:
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/shadi-barakat-781408265/"
  - title: "GitHub"
    url: "https://github.com/shadibarakat"

# Additional options for better SEO and customization
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge



