title: "Shadi Barakat"
logo: "/images/photo.jpeg"
description: "A journey through technology, coding, and creative projects."
show_downloads: true
theme: jekyll-theme-minimal

# Additional options for better SEO and customization
author: "Shadi Barakat"
email: "shadibarakat2004@gmail.com"
github_username: "shadibarakat" 
social_links:
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/shadi-barakat-781408265/" 
  - title: "GitHub"
    url: "https://github.com/shadibarakat" 
