# Site settings
title: Shadi Barakat Portfolio
description: "Welcome to my personal portfolio showcasing my projects, skills, and experiences."
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://yourusername.github.io" # The base hostname & protocol for your site

# Contact Information
email: shadibarakat2004@gmail.com
github_username: shadibarakat
linkedin_username: shadibarakat

# SEO settings
google_analytics: UA-XXXXXXX-X # Replace with your Google Analytics tracking ID
# plugins:
#   - jekyll-seo-tag

# Theme settings
theme: minima # Replace with your preferred Jekyll theme

# Social Links
social:
  
  github: shadibarakat
  linkedin: shadibarakat

# Portfolio settings
portfolio:
  - title: "GameGo Checkout System"
    description: "An intricate checkout system for a fictional store with multiple features."
    url: "/projects/gamego"
  - title: "Blackjack Game"
    description: "A simple blackjack game with a UI in progress."
    url: "/projects/blackjack"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude these files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
